pipeline {
  agent any
  tools {
    maven 'mvn'
    jdk 'JDK 8'
  }
  parameters {
    string(name: 'DEPENDENCY', description: 'Dependency to be detected (pattern: groupId:artifactId)', defaultValue: 'xerces:xercesImpl')
  }
  stages {
    stage('Initialize') {
      steps{
        sh '''
          echo "PATH = ${PATH}"
          echo "M2_HOME = ${M2_HOME}"
        '''
        sh 'mvn --version'
      }
    }
    stage('Test') {
      steps{
        sh 'cd scripts && ./detectDependency.sh $DEPENDENCY'
      }
    }
    stage('Clean up') {
      steps{
        deleteDir()
      }
    }
  }
}
