pipeline {
  agent any
  tools {
    maven 'mvn'
    jdk 'JDK 8'
  }
  stages {
    stage('Initialize') {
      steps{
        sh '''
          echo "PATH = ${PATH}"
          echo "M2_HOME = ${M2_HOME}"
        '''
        sh 'mvn --version'
      }
    }
    stage('Test') {
      steps{
        sh 'cd scripts && ./detectDuplicateDependencies.sh'
      }
    }
    stage('Clean up') {
      steps{
        deleteDir()
      }
    }
  }
}
