== Compliance Testing Program Roles and Responsibilities

=== CITE Subcommittee

The CITE Subcommittee (CITE SC) is a committee of the OGC TC consisting of OGC Members interested in the Compliance Testing Program. CITE SC has the following responsibilities:

* Guides the direction of the Compliance Testing Program.
* Reviews formal motions brought from OGC Members and OGC Staff.
* Submits formal motions and recommends approval by the TC.
* Reviews and approves roadmap.

=== Director of Interoperability Certification

The Director of interoperability Certification currently oversees the Compliance Testing Program and acts as the Compliance Testing Coordinator.

=== The Compliance Testing Coordinator

The Compliance Testing Coordinator (CTC) is the OGC Staff member responsible for coordinating and managing the operation of the Compliance Testing Program. The CTC has the following responsibilities:

* Propose candidate guidelines, policies, and procedures to the CITE SC.
* Coordinate the developing and maintenance of Compliance Test Packages.
* Coordinate the developing and maintenance of the Compliance Testing Engine.
* Propose candidate Compliance Test Packages to the CITE SC.
* Maintain guidelines and documentation of the Program.
* Select Reference Implementations (RI) for a Compliance Test Package and coordinate with the Reference Implementations developers for proper maintenance.
* Coordinate the Compliance Testing Evaluation of a Candidate Product.
* Manage and execute the interpretation and clarification process in collaboration with Standards Working Groups and Revision Working Groups.
* Manage and execute the dispute and challenge resolution process in collaboration with the +
appropriate working groups and OGC Member discussion forums.

=== The CITE Subcommittee, Technical and Planning Committees (PC)

With respect to compliance testing, the SC, TC and PC have the following responsibilities:

* Review and approve compliance testing guidelines, policies, and procedures.
* Review and select Compliance Test Packages including adaptations and provide an analysis of the adaptations to the CTC.
* Approve the release of Compliance Test Package versions.

=== OGC Compliance Team

The OGC Compliance Team is composed of OGC staff supporting this program. It includes the Compliance Testing Coordinator and other OGC staff.

For compliance testing, the OGC Staff has the following responsibilities:

* Support the Compliance Testing Coordinator related to the Compliance Testing Program.
* Administer the certification process including invoice processing and fees.
