== Introduction

=== Overview Document

This document describes the Open Geospatial Consortium (OGC) Compliance Testing Program. It describes the roles and responsibilities, compliance testing procedures, development of test packaging, and policies for developing and releasing the software use for testing.

The Compliance Test Program provides the resources, procedures, and policies to certify products for compliance with one or more OGC standards.

The primary purpose of the Compliance Testing Program is to increase systems interoperability while reducing technology risks by providing a process whereby compliance with OGC standards can be tested. The Compliance Testing Program provides confidence to technology vendors and buyers. Vendors feel confident that they are providing a product compliant with OGC standards, which will be easier to integrate and easier to market. Buyers fill confident that a compliant product will work with another compliant product based on the same OGC standard, regardless of which company developed the product.

=== Changes to this document

Any changes to this document are discussed at the OGC CITE Steering Committee (SC). Main changes are discussed at the Planning Committee (PC). Ultimately the Technical Committee (TC) votes for the release and approval of this document. A change request can also be submitted against this document via the OGC web site at http://www.opengeospatial.org/standards/cr.
